export const skills = {
  languages: [
    { name: 'Javascript', level: 8 },
    { name: 'ES6', level: 9 },
    { name: 'Typescript', level: 7 },
    { name: 'Solidity', level: 7 },
  ],
  ide: [
    { name: 'VScode', level: 9 },
    { name: 'Xcode', level: 6 },
    { name: 'Android Studio', level: 6 },
    { name: 'Remix', level: 8 },
  ],
  css: [
    { name: 'Styled Components', level: 8 },
    { name: 'MUI', level: 6 },
    { name: 'Native Base', level: 8 },
    { name: 'Antd', level: 8 },
    { name: 'Bootstrap', level: 9 },
    { name: 'CSS3', level: 9 },
    { name: 'SASS', level: 7 },
  ],
  softskills: [
    { name: 'Communication', level: 9 },
    { name: 'Empathy', level: 9 },
    { name: 'Adaptability', level: 9 },
    { name: 'Open-mindedness', level: 9 },
    { name: 'Problem-solving', level: 9 },
    { name: 'Humility', level: 9 },
    { name: 'Confidence', level: 9 },
    { name: 'Team work', level: 9 },
  ],
  tools: [
    { name: 'npm', level: 9 },
    { name: 'yarn', level: 9 },
    { name: 'Truffle', level: 8 },
    { name: 'Ganache', level: 8 },
    { name: 'Hardhat', level: 8 },
    { name: 'Redux', level: 8 },
    { name: 'Jira', level: 7 },
    { name: 'Notions', level: 7 },
    { name: 'Figma', level: 7 },
    { name: 'web3', level: 7 },
    { name: 'ethers', level: 7 },
    { name: 'GraphQl', level: 6 },
    { name: 'Apollo client', level: 6 },
    { name: 'Webpack', level: 5 },
  ],
  versioning: [
    { name: 'Git', level: 8 },
    { name: 'Github', level: 9 },
    { name: 'Gitlab', level: 8 },
  ],
  databases: [
    { name: 'RealTime database', level: 8 },
    { name: 'Firestore', level: 8 },
    { name: 'Postgres SQL', level: 6 },
    { name: 'Mysql', level: 6 },
  ],
  testing: [
    { name: 'Jest', level: 6 },
    { name: 'Enzyme', level: 6 },
    { name: 'React testing library', level: 7 },
  ],
  devops: [
    { name: 'Docker', level: 5 },
    { name: 'Travis', level: 5 },
    { name: 'Jenkins', level: 5 },
    { name: 'Heroku', level: 7 },
  ],
  libraries: [
    { name: 'React', level: 9 },
    { name: 'NodeJS (express)', level: 7 },
    { name: 'ReactNative', level: 9 },
    { name: 'NextJS', level: 5 },
  ],
};
