export const skills = {
  languages: [
    { name: 'javascript', level: 8 },
    { name: 'es6', level: 9 },
    { name: 'reactJS', level: 9 },
    { name: 'reactNative', level: 9 },
    { name: 'typescript', level: 7 },
    { name: 'expressJS', level: 7 },
    { name: 'solidity', level: 4 },
  ],
  ide: [
    { name: 'vscode', level: 9 },
    { name: 'xcode', level: 6 },
    { name: 'android studio', level: 6 },
    { name: 'remix', level: 8 },
  ],
  css: [
    { name: 'styled components', level: 8 },
    { name: 'MUI', level: 6 },
    { name: 'Native Base', level: 8 },
    { name: 'Antd', level: 8 },
    { name: 'Bootstrap', level: 9 },
    { name: 'css3', level: 9 },
    { name: 'sass', level: 7 },
  ],
  softskills: [
    { name: 'communication', level: 9 },
    { name: 'empathy', level: 9 },
    { name: 'adaptability', level: 9 },
    { name: 'open-mindedness', level: 9 },
    { name: 'problem-solving', level: 9 },
    { name: 'humility', level: 9 },
    { name: 'confidence', level: 9 },
    { name: 'team work', level: 9 },
  ],
  tools: [
    { name: 'npm', level: 9 },
    { name: 'yarn', level: 9 },
    { name: 'truffle', level: 5 },
    { name: 'ganache', level: 5 },
    { name: 'redux', level: 8 },
    { name: 'jira', level: 7 },
    { name: 'notions', level: 7 },
    { name: 'figma', level: 7 },
  ],
  versioning: [
    { name: 'git', level: 8 },
    { name: 'github', level: 9 },
    { name: 'gitlab', level: 8 },
  ],
  databases: [
    { name: 'Firebase', level: 8 },
    { name: 'Postgres SQL', level: 6 },
    { name: 'mysql', level: 6 },
    { name: 'graphQl', level: 6 },
    { name: 'apollo client', level: 6 },
  ],
  testing: [
    { name: 'jest', level: 6 },
    { name: 'enzyme', level: 6 },
    { name: 'react testing library', level: 7 },
  ],
  devops: [
    { name: 'docker', level: 5 },
    { name: 'travis', level: 5 },
    { name: 'jenkins', level: 5 },
    { name: 'heroku', level: 7 },
  ],
};
